<?php

/**
 * @file
 * Contains oyw_layouts.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function oyw_layouts_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the oyw_layouts module.
    case 'help.page.oyw_layouts':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Defines an extra layout') . '</p>';
      return $output;

    default:
  }
}
